In [1]:
import gurobipy as gp
import numpy as np
import time

from weightedPointControlPGDAR import *
from weightedPointControlGRb import *

In [2]:
# val = int(np.random.uniform(0,4000))
# print (val)
# np.random.seed(val)
# np.random.seed(2386)
nS = 5
nC = 3

A1_lb = np.random.random((nS,nC))
A1_ub = A1_lb + 0.1*np.random.random((nS,nC))
A2_lb = A1_lb
A2_ub = A1_ub
b_lb = np.random.random(nS)
b_ub = b_lb + 0.01 * np.random.random(nS)

Q = np.random.random((nS,nS))
Q = Q @ Q.T
q = np.random.random(nS)
R = np.zeros((nC,nC), dtype=np.float64)
S = np.zeros((nS, nC), dtype=np.float64)
r = np.zeros(nC, dtype=np.float64)

u_lb = - np.random.random(nC)
u_ub = np.random.random(nC)

w1 = np.random.random()
w2 = np.random.random()
w3 = np.random.random()

In [3]:
# Midpoint with GUrbobi
initMidpointProblem(u_lb, u_ub)
tC = time.time()
uGrb, cGrb = solveWeightedProblem(A1_lb, A1_ub, A2_lb, A2_ub, b_lb, b_ub, u_lb, u_ub,
                            2, Q, S, R, q, r, w1, w2, w3, verbose=False)
print(time.time() - tC)
print(uGrb)
print(cGrb)


--------------------------------------------
--------------------------------------------

Using license file /home/franck/gurobi.lic
Academic license - for non-commercial use only
0.0013968944549560547
[ 0.          0.         -0.30800512]
-2.3065454033128083


In [4]:
# Midpoint with Accelerated Projected Gradient With Gradient Restart Scheme
tC = time.time()
uAPG, cAPG = solveWeightedProblemAPGDAR(A1_lb, A1_ub, A2_lb, A2_ub, b_lb, b_ub, u_lb, u_ub,
                            2, Q, S, R, q, r, w1, w2, w3, epsTol=1e-8)
print(time.time() - tC)
print(uAPG)
print(cAPG)

3.3248953819274902
[ 0.          0.         -0.30800512]
-2.3065454033128088


In [5]:
# Check the optimistic problem
from optimisticControlGrb import *
initOptimisticProblem(nS, nC, None, None, None, None, None, u_lb, u_ub)
updateCost(Q, S, R, q, r)
tC = time.time()
uOp, cOp = solveOptimisticProblem(A1_lb, A1_ub, A2_lb, A2_ub, b_lb, b_ub,
            u_lb, u_ub, 2, verbose=False)
print(time.time() - tC)
print(uOp, cOp)

0.014175653457641602
[ 0.          0.         -0.30800512] 7.960088847859777
